name: AdvancedMLGRush
version: ${project.version}
main: de.febanhd.mlgrush.MLGRush
author: FebanHD
description:

commands:
  setupmap:
  setqueue:
  setlobby:
  tptemplate:
  leave:
  stats:
  sortinv: